config/routes.rb
Rails.application.routes.draw do

  # resources :states, only: [ :index ]
#     resources :rivers, only: [ :index, :show ]
#   end
#
  namespace :admin do
    resources :states do
      resources :rivers
    end
  end

resources :users, only: [:new, :create, :show]

end

app/models/application_fee.rb
class ApplicationFee < ActiveRecord::Base
  has_many :rivers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_website.rb
class ApplicationWebsite < ActiveRecord::Base
  has_many :rivers
end

app/models/boat_ramp.rb
class BoatRamp < ActiveRecord::Base
  has_many :put_ins, class_name: 'River', foreign_key: :put_in
  has_many :take_outs, class_name: 'River', foreign_key: :take_out
end

app/models/managing_agency.rb
class ManagingAgency< ActiveRecord::Base
  has_many :rivers
end

app/models/permit_cost.rb
class PermitCost < ActiveRecord::Base
  has_many :rivers
end

app/models/permit_type.rb
class PermitType < ActiveRecord::Base
  has_many :rivers
end

app/models/river.rb
class River < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :put_in, presence: true
  validates :take_out, presence: true
  validates :application_fee, presence: true
  validates :application_website, presence: true
  validates :permit_cost, presence: true
  validates :permit_type, presence: true
  validates :length, presence: true

  belongs_to :application_fee
  belongs_to :application_website
  belongs_to :managing_agency
  belongs_to :permit_cost
  belongs_to :permit_type
  belongs_to :state

  belongs_to :put_in, class_name: 'BoatRamp', foreign_key: :put_in
  belongs_to :take_out, class_name: 'BoatRamp', foreign_key: :take_out

end

app/models/state.rb
class State < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :rivers, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true

  enum role: %w(default admin)

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  
end

app/controllers/admin/rivers_controller.rb
class Admin::RiversController < Admin::BaseController

  def new
    @state = State.find(params[:state_id])
    @river = River.new
  end

  def create
    @state = State.find(params[:state_id])
    @river = @state.rivers.new(river_params)
    if @river.save
      flash[:success] = "#{@river.name} successfully added"
      redirect_to admin_state_rivers_path
    else
      flash[:incomplete] = "Please fill in every form item."
      render :new
    end

  end

  def show
    @river = River.find(params[:id])
  end

  def edit
    @state = State.find(params[:state_id])
    @river = River.find(params[:id])
  end

  def update
    if @river = River.update(river_params)
      flash[:updated] = "#{@river.name} successfully updated"
      redirect_to admin_state_path(@river.state)
    else
      render :edit
    end
  end

  def destroy
    @river = River.find(params[:id]).destroy
    flash[:destroy] = "River successfully deleted"
    redirect_to admin_state_path(@river.state)
  end

private

  def river_params
    params.require(:river).permit(:name, :put_in, :take_out, :permit_cost,
                                  :permit_type, :length, :managing_agency,
                                  :application_website)
  end

end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::BaseController

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)
    if @state.save
      flash[:success] = "#{@state.name} successfully added!"
      redirect_to admin_states_path
    else
      render :new
    end
  end

  def index
    @states = State.all
  end

  def show
    @state = State.find(params[:id])
  end

  def edit
    @state = State.find(params[:id])
  end

  def update
    @state = State.new(state_params)
    if @state.save
      flash[:update] = "#{@state.name} successfully updated."
      redirect_to admin_states_path
    else
      render :edit
    end
  end

  def destroy
    state = State.find(params[:id])
    state.destroy
    flash[:destroy] = "#{state.name} successfully deleted."
    redirect_to admin_states_path
  end

private

  def state_params
    params.require(:state).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Successfully logged in!"
      redirect_to user_path(@user)
    else
      flash[:error] = "Could not create account"
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/rivers/_form.html.erb
<%= form_for [:admin, @state, @river] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :put_in %>
  <%= f.text_field :put_in %>
  <%= f.label :take_out %>
  <%= f.text_field :take_out %>
  <%= f.label :application_fee %>
  <%= f.text_field :application_fee %>
  <%= f.label :permit_cost %>
  <%= f.text_field :permit_cost %>
  <%= f.label :permit_type %>
  <%= f.text_field :permit_type %>
  <%= f.label :length %>
  <%= f.text_field :length %>
  <%= f.label :managing_agency %>
  <%= f.text_field :managing_agency %>
  <%= f.label :application_website %>
  <%= f.text_field :application_website %>
  <%= f.submit %>
<% end %>

app/views/admin/rivers/edit.html.erb
<h1>Edit <%= @river.name %></h1>

<%= render partial: "form" %>

app/views/admin/rivers/new.html.erb
<h1>Create New River</h1>

<%= render partial: "form" %>

app/views/admin/rivers/show.html.erb
<h1><%= @river.name %></h1>

<ul>
  <li>Put-In: <%= @river.put_in.name %></li>
  <li>Take-Out: <%= @river.take_out.name %></li>
  <li>Application Fee: <%= @river.application_fee.price %></li>
  <li>Permit Cost: <%= @river.permit_cost.price %></li>
  <li>Permit Type: <%= @river.permit_type.name %></li>
  <li>Length: <%= @river.length %> Miles</li>
  <li>Managing Agency: <%= @river.managing_agency.name%></li>
  <li>Application Website: <%= @river.application_website.website%></li>
</ul>

<div class="btn">
  <%= link_to "Edit", edit_admin_state_river_path(@river.state, @river) %>
</div>
<div class="btn">
  <%= link_to "Delete", admin_state_river_path(@river.state, @river), method: "delete" %>  
</div>

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name%>

  <%= f.submit %>
<% end %> 

app/views/admin/states/edit.html.erb
<h1>Edit <%= @state.name %></h1>

<%= render partial: "form" %>

app/views/admin/states/index.html.erb
<h1>All states</h1>

<div class="states">
  <% @states.each do |state| %>
  <div class="state">
    <%= link_to state.name, admin_state_path(state) %>
  </div>
  <% end %>
</div>

<div class="btn">
  <%= link_to "Add State", new_admin_state_path %>
</div>

app/views/admin/states/new.html.erb
<h1>Add a New State</h1>

<%= render partial: "form" %>

app/views/admin/states/show.html.erb
<h1><%= @state.name %></h1>

<div class="river-trips-container">
  <% @state.rivers.each do |river| %>
  <div class="river-trips">
    <%= link_to river.name, admin_state_river_path(@state, river) %>
  </div>
  <% end %>
</div>


<div class="btn">
  <%= link_to "Add River", new_admin_state_river_path(@state) %>
</div>

<div class="btn">
  <%= link_to "Edit State", edit_admin_state_path(@state) %>
</div>

<div class="btn">
  <%= link_to "Delete State", admin_state_path(@state), method: "delete" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RiverRite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="new-user">

  <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email%>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation%>

    <%= f.submit "Create Account", class: 'btn btn-success' %>
  <% end %>

</div>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %>!</h1>